sudo: required

language: node_js
node_js:
  - "11.10.1"

services:
  - docker


before_install:
  - docker build -t marcell0major/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run marcell0major/react-test npm test -- --coverage

after_success:
  - docker build -t marcell0major/multi-client ./client
  - docker build -t marcell0major/multi-nginx ./nginx
  - docker build -t marcell0major/multi-server ./server
  - docker build -t marcell0major/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push marcell0major/multi-client
  - docker push marcell0major/multi-nginx
  - docker push marcell0major/multi-server
  - docker push marcell0major/multi-worker